services:

    ### App (php, nodejs, python) (ports: php-fpm 9000, octane 8000, vite 5173)
    social_installer-app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                TZ: ${WORKSPACE_TIMEZONE}
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        container_name: social_installer-app
        hostname: social_installer-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        ports:
            - "5174:5173"
        depends_on:
            - social_installer-mariadb
            - social_installer-redis
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
        volumes:
            - ./:/var/www
            - ./docker/app/php_additional.ini:/usr/local/etc/php/conf.d/additional.ini
            - ./docker/app/.zshrc:/home/www-data/.zshrc
            - ./docker/app/bin:/home/www-data/bin
            - ~/.ssh:/home/www-data/.ssh:ro
            - ~/.gitconfig:/home/www-data/.gitconfig
        networks:
            - social_installer-network

    ### Nginx (ports: nginx 80)
    social_installer-nginx:
        image: nginx:stable-alpine
        container_name: social_installer-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "9090:80"
        depends_on:
            - social_installer-app
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/log:/var/log/nginx
        networks:
            - social_installer-network

    ### MariaDB (ports: mysql 3306)
    social_installer-mariadb:
        image: mariadb:10.11-rc
        container_name: social_installer-mariadb
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306" # Отключен внешний доступ
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - social_installer-mariadb-data:/var/lib/mysql
            - ./docker/mariadb/sql:/docker-entrypoint-initdb.d
        networks:
            - social_installer-network

    ### Redis (ports: redis 6379)
    social_installer-redis:
        image: redis:alpine3.18
        container_name: social_installer-redis
        restart: unless-stopped
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
        volumes:
            - social_installer-redis-data:/data
            - ./docker/redis/log:/log
        command: ["redis-server"]
        networks:
            - social_installer-network

    ### phpMyAdmin (ports: gui 80)
    social_installer-phpmyadmin:
        image: phpmyadmin:5.2
        container_name: social_installer-phpmyadmin
        restart: unless-stopped
        ports:
            - "${PHPMYADMIN_PORT:-8010}:80"
        environment:
            PMA_HOST: social_installer-mariadb
            UPLOAD_LIMIT: 512M
        networks:
            - social_installer-network

networks:

    social_installer-network:
        driver: bridge

volumes:

    social_installer-mariadb-data:
        driver: local

    social_installer-redis-data:
        driver: local

    social_installer-mailpit:
        driver: local